# Varsayilan degerler. Ortama gore -f ile ezilir.
replicaCount: 3

image:
  repository: k8s-lab-app
  tag: "2.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  ORTAM: "production"
  LOG_SEVIYE: "warn"
  KARSILAMA: "Selam"

secret:
  DB_PAROLA: "degistir-beni"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: false
  host: app.local
