kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # ingress-nginx HTTP
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443   # ingress-nginx HTTPS
        hostPort: 8443
        protocol: TCP
  - role: worker
  - role: worker
