-- When a signature carrying this connection's identity was first seen.
--
-- The column that decides whether the rendered policy rejects or records.
-- Empty means "not yet", and every connection starts there: enforcing before
-- the tenant's workflow has ever produced a signed image refuses their next
-- deploy, which is connecting a repository and having deploys stop.
--
-- Empty rather than NULL, matching the other timestamps in these schemas, which
-- are text and compare lexicographically. Go reads "" back as the zero time and
-- Connection.Verified is false for it, so the default is the safe state without
-- a backfill: every row written before this column existed is, correctly, one
-- nothing has verified.
ALTER TABLE forge_connection ADD COLUMN first_signature_at TEXT NOT NULL DEFAULT '';
