apiVersion: v1
kind: ServiceAccount          # pod'un kimligi
metadata:
  name: okuyucu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role                    # Role = TEK namespace icinde yetki
metadata:
  name: pod-okuyucu
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]    # sadece okuma. create/delete YOK
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding             # kimlik <-> yetki baglantisi
metadata:
  name: okuyucu-pod-okur
  namespace: default
subjects:
  - kind: ServiceAccount
    name: okuyucu
    namespace: default
roleRef:
  kind: Role
  name: pod-okuyucu
  apiGroup: rbac.authorization.k8s.io
